### ISSUE TITLE
case statement perf in DecodeByType

### ISSUE THREAD

**Issue by NickLarsen** [maxmind/MaxMind-DB-Reader-dotnet#10]
I added an array of counters to the `DecodeByType` function, one for each `ObjectType`, and noticed that the _vast_ majority of values decoded are strings when using the GeoIP2-City.mmdb file.  You can save a lot of branches if [`ObjectType.Utf8String`](https://github.com/maxmind/MaxMind-DB-Reader-dotnet/blob/master/MaxMind.Db/Decoder.cs#L164) is the first case checked.  It doesn't make a lot of difference when you're looking up one IP at a time, but when you're looking up millions at a time it's pretty noticeable (almost half an hour shaved over 30MM lookups when passing the file in as a memory stream).

**Comment by oschwald** [comment]
Doesn't the compiler just create a jump table, in which case the order shouldn't matter? Perhaps it only does this in certain circumstances.
