### ISSUE TITLE
Async Support?

### ISSUE THREAD

**Issue by niemyjski** [maxmind/MaxMind-DB-Reader-dotnet#11]
It would be nice to be able to create a DatabaseReader async.

**Comment by luisrudge** [comment]
:+1:  to that

**Comment by niemyjski** [comment]
:+1:

**Comment by cotzo** [comment]
+1

**Comment by Quppa** [comment]
I added an async `CreateReader` method with overloads for files and streams to mirror the existing constructors.

Caveats:
- These methods will always load the data into memory (memory-mapped files won't be used).
- `DatabaseReader` in [GeoIP2](https://github.com/maxmind/GeoIP2-dotnet) will need to be updated to optionally use these methods for this to be of any use. I'm happy to do that if/once the above changes are accepted for this project.

**Comment by oschwald** [comment]
This was done in #44.
