### ISSUE TITLE
List of all model classes

### ISSUE THREAD

**Issue by Bluscream** [maxmind/MaxMind-DB-Reader-dotnet#151]
Where can i find all the model classes? Are they not in the nuget package?

**Comment by oschwald** [comment]
This is a low-level library that works with any MMDB database. It does not include any model classes. It sounds like maybe you want [MaxMind.GeoIP2](https://www.nuget.org/packages/MaxMind.GeoIP2), which has model classes for the MaxMind-provided databases.

**Comment by Bluscream** [comment]
> This is a low-level library that works with any MMDB database. It does not include any model classes. It sounds like maybe you want [MaxMind.GeoIP2](https://www.nuget.org/packages/MaxMind.GeoIP2), which has model classes for the MaxMind-provided databases.

Ahh thank you very much :pray:
