### ISSUE TITLE
Re-reading mmdb file

### ISSUE THREAD

**Issue by Buffele** [maxmind/MaxMind-DB-Reader-dotnet#162]
What is the proper way to re-read a mmdb file for a running application without restarting it?

```csharp
// Initializing the reader
var reader = new Reader(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "conf//GeoLite2-ASN.mmdb"));

// Somewhere in the code, GeoLite-ASN.mmdb has changed, we want to reload it.
reader.Dispose();
reader = new Reader(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "conf//GeoLite2-ASN.mmdb"));
```

Is this the way to go?

**Comment by oschwald** [comment]
Yes, that should work. If your application is multi-threaded, I would suggest introducing some locking or otherwise defer the dispose until you are certain it is no longer being used.

**Comment by Buffele** [comment]
Thanks!

That should also exactly apply to https://github.com/maxmind/GeoIP2-dotnet, for the DatabaseReader class, right?

**Comment by oschwald** [comment]
Yes, that is correct.
