### ISSUE TITLE
Publishing a new beta 3 version on nuget?

### ISSUE THREAD

**Issue by sarus** [maxmind/MaxMind-DB-Reader-dotnet#24]
Hello,

We're interested in using the latest PR you accepted to get access to an IPs routing prefix.  I wanted to check and see if you would be willing to publish a beta version on nuget or if you think this will hit 2.0 release soon and be made generally available.  We're actually using GeoIP2-dotnet rather than the DB reader directly right now but we're willing to use both to get the routing prefix info until a version of GeoIP2-dotnet is released that includes the latest DB reader.

If you think it'll be a while before the beta version is available via Nuget that is not a problem and we'll build a version ourselves until he official version is available.  I just wanted to get a sense of timing so we know which option to pursue.

Thank you!

**Comment by oschwald** [comment]
Ah, thanks for the reminder. I can do a beta release with that change today.

**Comment by oschwald** [comment]
Now available on [NuGet](https://www.nuget.org/packages/MaxMind.Db/2.0.0-beta3).
