### ISSUE TITLE
Support reading .gz file directly

### ISSUE THREAD

**Issue by RobThree** [maxmind/MaxMind-DB-Reader-dotnet#25]
Could you add support for reading the .gz file **directly** (without having to decompress first)?

I've done [similar in one of my projects](https://github.com/RobThree/NGeoNames/blob/master/NGeoNames/GeoFileReader.cs#L76). The change involves not very much more than wrapping the stream in a `GZipStream`.

So instead of writing:

`using (var reader = new Reader("GeoIP2-City.mmdb"))`

I could write:

`using (var reader = new Reader("GeoIP2-City.mmdb.gz"))`

The same can, currently, be achieved with the following:

```
using (var fs = File.OpenRead("GeoIP2-City.mmdb.gz"))
using (var gs = new GZipStream(fs, CompressionMode.Decompress))
using (var r = new Reader(gs))
{
    // ...
}
```

~~But this bypasses the `ArrayBuffer` or `MemoryMapBuffer`, both of which are internal.~~
This is not true; the [ctor involved passes it on to an ArrayBuffer](https://github.com/maxmind/MaxMind-DB-Reader-dotnet/blob/4147d22616483c880c751cd8cd0eb52ac4a485cb/MaxMind.Db/Reader.cs#L86) which I didn't notice at first.

You could:
- 'autodetect' wether it's a gz file by 
  - (simple) looking at the filename (e.g. `.EndsWith(".gz")`)
  - looking for a signature (first three bytes should be `1F 8B 08`)
- add an (optional, defaulting to "plain" or "autodetect") enum argument specifying the desired type (like [this](https://github.com/RobThree/NGeoNames/blob/eaaa9c867411ddadfaf2bfffa73c0dab977d106d/NGeoNames/FileType.cs#L7))

or a combination of the above (where you add another enum value besided `Plain` and `GZip`; like `AutoDetect`).

I'm willing to implement it and make a PR; I'm not (that) familiar with this codebase yet so that might take a little while.

**Comment by oschwald** [comment]
Besides saving a few lines of code when using the library with gzip files, I am not sure this would provide many benefits. Supporting compressed files does not compose well with the file modes (e.g., we cannot memory map a compressed file and use that). This library would either need to read the whole thing into memory or create a temporary file. The former is equivalent to what is happening when you pass in the stream and the latter would likely add complexity and create complications.

**Comment by RobThree** [comment]
> Besides saving a few lines of code when using the library with gzip files, I am not sure this would provide many benefits.

No, there wouldn't be any big benefits; it was more meant as a "convenience method/overload". It would, indeed, be best (*if implemented at all*) to extract the .gz to a temporary file. From there on you could use the `ArrayBuffer` or `MemoryMapBuffer` as is currently done.

> The former is equivalent to what is happening when you pass in the stream and the latter would likely add complexity and create complications.

Yes; agreed. I didn't notice the `ArrayBuffer` being used when passing in the stream (hence the update in the original issue where I striked it out (~~But ... internal~~)). I guess leaving the decompression to the user (of the library) is the better choice. Consider this issue resolved / never happened :wink:

**Comment by am11** [comment]
We can probably investigate the related new contract added in CoreFX `System.Buffers`:

Repo: https://github.com/dotnet/corefx/tree/master/src/System.Buffers
NuGet: https://www.nuget.org/packages/System.Buffers/4.0.0-rc2-24027
*(supports both NETStandard and .NET Framework 4.5 TFMs)*

The docs of this particular contract are missing ATM from http://dotnet.github.io/api/index.html, however, we can get some ideas from the unit tests available in the repo.

**Comment by oschwald** [comment]
I am going to close this as MaxMind no longer provides links to `.gz` files. It does provide `.tar.gz` files that include the license. These would be somewhat more cumbersome to unpack and most users would be better off unpacking them to disk so that they don't need to read the whole file into memory.
