### ISSUE TITLE
Featuring NetCore (CoreCLR) port

### ISSUE THREAD

**Issue by am11** [maxmind/MaxMind-DB-Reader-dotnet#26]
Hello,

I have ported this lib to CoreCLR: https://github.com/am11/MaxMind-DB-Reader-dotnet/tree/coreclr-port.

At the moment, it builds with latest dotnet/cli (https://github.com/dotnet/cli#installers-and-binaries) and VS15 preview only; as VS14.2 (sometimes known as: VS2015 Update 2) does not have CLI support yet https://github.com/dotnet/cli/issues/1556.

To build this with dotnet/cli in text mode (without VS15 preview) using Windows Command Prompt:

* First download and install Windows binary https://github.com/dotnet/cli#installers-and-binaries
* `git clone https://github.com/am11/MaxMind-DB-Reader-dotnet -b coreclr-port`
* `cd MaxMind-DB-Reader-dotnet`
* `cd MaxMind.DB`
* `dotnet restore && dotnet build`
* `cd ..\MaxMind.Benchmark`
* `dotnet restore && dotnet build`

To run benchmark with net451 TFM CLR:

* `dotnet run -f net451`

To run benchmark with CoreCLR:

* `dotnet run -f netcoreapp1.0` or simply `dotnet run` (as netcoreapp1.0 *target framework moniker* is default in dotnet CLI)

---

Random notes: 😺
* `.csproj`s are replaced with `.xproj`.
* The library project has `netstandard1.4` TFM, while benchmark and test are Console projects, aka `netcoreapp` using `netcoreapp1.0` TFM.
* There are `imports` statements in all three PJs (`project.json`s), which would probably be deprecated once the long overdue dotner-core RC2 is out.
* Test project is Console app because the Nunit-lite runner requires it to be a console project (http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/ <- the difference is I changed the main signature to `static Main` so to emit a pure console app).
  * Tip: to make any `lib / dll`-emitting `xproj` to `exe`-emitting `xproj`, add `  `"buildOptions": { "emitEntryPoint": true },` line in `project.json` and acquire dependency on `System.Console`.
    * `buildOptions` property used to known as `compilationOptions` in DNX days, which is deprecated in dotnet CLI.
      * For latest JSON schema of `project.json`, refer to https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project.json (this will be published to SchemaStore website, which VS JSON uses by default).
* I used https://github.com/microsoft/dotnet-apiport and https://github.com/dotnet/corefx as reference point for all the `#if`-`#elif` preprocessor directive changes to satisfy NetCore std surface area.

Sad part: :crying_cat_face:
* While all three projects succeed `dotnet restore ; dotnet build` and Benchmark runs fine with `dotnet run` for `netcoreapp1.0` moniker, I get error similar to #4 when I execute the test project with `dotnet run`. Seems like the mmdb file in `TestData/` directory is corrupted.

---

If this is acceptable progress, I can add TFM for `mono` and Unices' runtimes in `project.json`s and send a PR. :rocket:

Otherwise :bulb:, feel free to cherry-pick and use as you see fit. My ultimate interest is to run [GeoIP2-dotnet](https://github.com/maxmind/GeoIP2-dotnet) under CoreCLR, for which I have some local patches awaiting DB-Reader dependency ready for CoreCLR.

Thanks for your patience. :candy:

**Comment by oschwald** [comment]
Thanks! CoreCLR support is definitely something that we would like. I haven't had time to play around with this, but the changes look largely reasonable. To be mergeable into master, the AppVeyor and Travis configurations will need to be updated to appropriately test the different builds. Also, the Nuspec may need updating.

**Comment by am11** [comment]
Thanks for the input @oschwald!
I read the documentation of `dotnet pack` command: https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-pack/README.md, and tested it out. It is super easy. We do not need nuspec file anymore. All the project characteristics are defined in the project.json.

```cmd
git clone https://github.com/am11/MaxMind-DB-Reader-dotnet -b coreclr-port
cd MaxMind-DB-Reader-dotnet
cd MaxMind.Db

dotnet restore
dotnet pack

:: ennd ov' story ->
:: it compiles and generates the assemblies and symbol packages

Producing nuget package "MaxMind.Db.2.6.0" for MaxMind.Db
MaxMind.Db -> C:\Users\Adeel\source\repos\MaxMind-DB-Reader-dotnet\MaxMind.Db\bin\Debug\MaxMind.Db.2.6.0.nupkg
Producing nuget package "MaxMind.Db.2.6.0.symbols" for MaxMind.Db
MaxMind.Db -> C:\Users\Adeel\source\repos\MaxMind-DB-Reader-dotnet\MaxMind.Db\bin\Debug\MaxMind.Db.2.6.0.symbols.nupkg
```

Personally, I have found he builtin commands' documentation quite simple to follow: https://github.com/dotnet/cli/tree/master/src/dotnet/commands.

For CI, there are samples on this issue for both AppVeyor and TravisCI: https://github.com/dotnet/cli/issues/2113. As per @akoeplinger's input there, it appears that we will need to use `sudo` to install CLI until RC2 is released, at which point CLI feed will be whitelisted on TravisCI servers.

Meanwhile, I am running the latest nightly `v1.0.0-rc2-002543`:

* Binary Installer: https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-win-x64.latest.exe
* SDK installer: https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe

from the [CLI README](https://github.com/dotnet/cli#installers-and-binaries) and we need both to be able to build and run CoreCLR apps. We can configure the CI script accordingly. I will dig into it when I get some spare cycles and will update the progress soon.

**Comment by am11** [comment]
@oschwald, I have configured both the CIs to test .NET Core.

<kbd>Commit</kbd> 2b367316
<kbd>Travis CI</kbd> https://travis-ci.org/am11/MaxMind-DB-Reader-dotnet/builds/128413918
<kbd>AppVeyor CI</kbd> https://ci.appveyor.com/project/am11/maxmind-db-reader-dotnet/build/1.0.73

On AppVeyor, net451 and netcoreapp1.0 is configured for Windows.
On Travis CI, only netcoreapp1.0 is configured for OS X 10.0 and Ubuntu 14.04 (trusty). While Mono was supported on aspnet/DNX, its successor dotnet/cli is yet to bring the support (tracking issue: https://github.com/dotnet/cli/issues/1613)

I will open a PR for your review. 8-)

**Comment by oschwald** [comment]
Thanks for all of your work on this! :+1: I'll take a closer look early next week.
