### ISSUE TITLE
Decoder.DecodePointer() unclear ternary op

### ISSUE THREAD

**Issue by Dmitry-Me** [maxmind/MaxMind-DB-Reader-dotnet#36]
Decoder.DecodePointer() contains this code:

    var b = pointerSize == 4 ? 0 : size & 0x7;

This code would be easier to read if it had composite parts of ternary op enclosed in braces:

    var b = (pointerSize == 4) ? 0 : (size & 0x7);

**Comment by oschwald** [comment]
I don't find the existing code particularly unclear, but if you submitted this as a PR, I'd be happy to merge it. I am going to close the issue.
