### ISSUE TITLE
System.IO.IOException: The process cannot access the file 'D:\home\site\wwwroot\Content\GeoLite2-City.mmdb' because it is being used by another process.

### ISSUE THREAD

**Issue by Alkasai** [maxmind/MaxMind-DB-Reader-dotnet#4]
I am building ASP.NET MVC 5 application and I ninject the reader into my service with the following code:
`kernel.Bind(typeof(Reader)).ToSelf().InSingletonScope().WithConstructorArgument("file", ninject => HttpContext.Current.Server.MapPath("/Content/GeoLite2-City.mmdb"));`

I am making it into a singleton following the advice to "creating one `Reader` object and sharing that among threads".

Now when I deploy it to azure it sometimes causes `IOException` and freezes the server, because it's not able to construct a Controller with this service, due to file being used by another process.

I am not sure if that a bug or if I'm not using it correctly.

**Comment by anjdreas** [comment]
I'm getting the same problem. I've tried both approaches:

* `using()` pattern to create/dispose DatabaseReader on every lookup
* Singleton pattern for creating DatabaseReader once

I believe this is due to running multiple instances in Azure, but I have not confirmed this yet. I am not able to reproduce when running locally. I'll try @oschwald 's approach.

**Comment by anjdreas** [comment]
It seems using `FileAccessMode.Memory` instead of `FileAccessMode.MemoryMapped` helped. This way I don't have problems with MemoryMappedFile created from two Azure instances resulting in an IOException in one of them.

**Comment by oschwald** [comment]
Are you using 1.2.0 of this API?

**Comment by Alkasai** [comment]
@anjdreas i don't remember what we end up doing, i haven't touched that code in a year... but looking at the code we end up creating a singleton instance of the location service, per server:

`kernel.Bind(typeof(YOUR_LOCATION_Service)).To(typeof(YOUR_LOCATION_Service)).InSingletonScope().WithConstructorArgument("path", ninject => HttpContext.Current.Server.MapPath("YOUR_MMDB_FILE.mmdb"));`

and the service would load the file in the constructor using a file stream:
            `using (var fstream = File.OpenRead(path))
            {
                LocationReader = new Reader(fstream);
            }`

starting of a new server was a bit slow, because it had to load the file in memory, but that was only happening once on scaling the servers.

hope that helps.

**Comment by anjdreas** [comment]
Thanks for the response, but so far things are looking good with my workaround.

@oschwald I'm currently using these nugets:

<package id="MaxMind.Db" version="1.0.1.0" targetFramework="net451" />
 <package id="MaxMind.GeoIP2" version="2.2.0.0" targetFramework="net451" />

**Comment by oschwald** [comment]
Ah, that is a pretty old version of `MaxMind.Db`. 1.1.0 has some fixes that may help with the particular issue you had.
