### ISSUE TITLE
Registered Country

### ISSUE THREAD

**Issue by oliverherdener** [maxmind/MaxMind-DB-Reader-dotnet#40]
The CountryResponse does not contain a valid/meaningful RegisteredCountry property.

var dbfile = "GeoIP2-Country.mmdb";
DatabaseReader reader = new DatabaseReader(dbfile);

CountryResponse countryResponse;
if (reader.TryCountry("8.8.8.8", out countryResponse))
{
	Console.WriteLine("Country ISO code: " + countryResponse.Country.IsoCode);
	Console.WriteLine("RegisteredCountry ISO code: " + **countryResponse.RegisteredCountry.IsoCode**);
}
else
{
	Console.WriteLine("error in db query");
}

countryResponse.RegisteredCountry.IsoCode is null but should be set to "US" in this case.

**Comment by oschwald** [comment]
Thanks for reporting this. I confirmed the issue and it should be fixed in the next release, which should hopefully be soon.
