### ISSUE TITLE
Iterate all records

### ISSUE THREAD

**Issue by jjxtra** [maxmind/MaxMind-DB-Reader-dotnet#46]
There is no way to do a foreach (var item in reader) {} without writing code against the maxmind binary format, which in my opinion is a waste of time.

This would be very helpful for building custom data structures, such as a country with it's list of ip ranges.

**Comment by oschwald** [comment]
You could iterate over the whole database currently using this method:

https://github.com/maxmind/MaxMind-DB-Reader-dotnet/blob/master/MaxMind.Db/Reader.cs#L184

The prefix length will tell you where the start of the next record is. I agree that it is not as convenient as an iterator though.

**Comment by jjxtra** [comment]
So how do I know the next ip address from the prefix length? I assume I start by passing an ip of 0.0.0.0?

**Comment by oschwald** [comment]
Yes, You could start at `0.0.0.0`. Then you would use the prefix length to find the last IP in the network and increment that IP by 1 for the start of the next network.

**Comment by jjxtra** [comment]
So basically convert prefix length to uint32_t and add one and turn back into an ip address? What about ipv6?

**Comment by jjxtra** [comment]
This is a slight headache as I have to increment both ipv4 and ipv6 addresses. Would love to have a foreach (...) option on the reader interface.

**Comment by oschwald** [comment]
I wouldn't expect iterating the binary database to be faster than a CSV. With the CSV, you can go through the file in a linear order. With the binary database, there will be a lot of seeking as you read the data records.

**Comment by jjxtra** [comment]
Sure, but this is on a 960 EVO Pro SSD. The country file is about 3 MB in size. That should more or less fit in the CPU cache.

At any rate I have switched to using the csv files directly with my own binary files. Thanks for your assistance!

**Comment by jjxtra** [comment]
Would you accept a pull request with the iterate function added?

**Comment by oschwald** [comment]
Yes, a reasonably implemented PR for this functionality would be accepted. If it is done in the reader itself, it should be done by walking the search tree directly rather than using the prefix length. You can see one [example of this being done in the unofficial Go reader](https://github.com/oschwald/maxminddb-golang/blob/master/traverse.go). I believe the Perl reader also implements something similar.

**Comment by jjxtra** [comment]
Pull request sent, I would love feedback.

**Comment by jjxtra** [comment]
Just as an FYI I am able to enumerate the full cities database in about 15 seconds now, versus over 10 minutes before. This is with the latest pull request.

**Comment by jjxtra** [comment]
Is there anything else needed for the pull request? I'd love to go back to using the NuGet package instead of my custom build.

**Comment by oschwald** [comment]
I haven't found time to look at it closely yet. One potential area of concern is that unlike `Find`, it doesn't use parameterized types. `Data` is a `Dictionary<string, object>`. Making it more similar to `Find` would make it more generally useful. Also, the MMDB format does not force the outer data structure to be a map, so it is possible `Dictionary<string, object>` would not work at all for some databases.

**Comment by jjxtra** [comment]
Ok I will make it do a generic type.

-- Jeff

**Comment by jjxtra** [comment]
Updated the pull request to use a generic type.

**Comment by oschwald** [comment]
Thanks for the reminder. I'm going to make sure I get to doing a close review and test of it by Friday.

**Comment by oschwald** [comment]
Closing since you added this in #47.
