### ISSUE TITLE
IOException when using Parallel

### ISSUE THREAD

**Issue by RichTeaMan** [maxmind/MaxMind-DB-Reader-dotnet#5]
Hi everyone,

I've been using MaxMind GeoIP2 for .NET from Nuget to process IP addresses but kept getting an IOException - 'IOException: Not enough storage is available to process this command'.

I downloaded the source code and did some sleuthing, and the problem appears to be with the use of ThreadLocal<Stream> in MaxMind.Db.Reader. ThreadLocal creates a new Stream every time a new thread uses the Reader but the Streams are not cleaned up until the entire Reader is disposed. ThreadLocal does not seems to have any capabilities to dispose dormant values until the entire object is collected.

I have been using Parallel.ForEach to give my code multithreading so I have no direct access to the threads, but it is clear that .NET has has no bias to reusing threads. As you can see from the screenshot this exception occurred after initialising 45 separate Streams.

This problem only occurred for me on 32 bit builds after 10 - 30 minutes. 64 bit builds didn't crash over the several hours I tested, although I suspect the same exception would happen eventually. As I intend to run this program over several days I want the code to be as solid as possible.

For now I've worked around the problem by managing my own threads, although I'd like to use the Parallel.ForEach again if a fix is available.

Let me know if you need any more information.
Thanks,
Tom
![maxmindexception](https://cloud.githubusercontent.com/assets/3968139/5185421/5deb6fda-74b7-11e4-8983-433071d415e5.png)

**Comment by sachinkesharwani** [comment]
ExceptionType : System.IO.IOException
StackTrace    :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at MaxMind.Db.Reader.<>c__DisplayClass19_1.<.ctor>b__1()
   at System.Threading.ThreadLocal`1.CreateValue()
   at System.Threading.ThreadLocal`1.get_Value()
   at MaxMind.Db.Reader.FindMetadataStart()
   at MaxMind.Db.Reader.InitMetaData()
   at MaxMind.Db.Reader..ctor(String file, FileAccessMode mode)
   at MaxMind.GeoIP2.DatabaseReader..ctor(String file, FileAccessMode mode)
   at TrafficSplitterRepository.getUserDetailFromMaxMind() in c:\inetpub\wwwroot\CBC 6.3\Website\App_Code\TrafficSplitterRepository.cs:line 711


Facing the same issue while reading the maxmind db any help is appreciated

**Comment by oschwald** [comment]
If you build it as 64 bit, you will likely not run into this or other issues. I would however like to see this fixed. I think we will just need to not use ThreadLocal. I wish there was a stateless way to access memory maps in safe code, but I guess we will just need to create a stream view per request.

**Comment by sachinkesharwani** [comment]
The code I am building it is on 64bit windows 8.1.Still the issue persist.However how can i write the stream view per request as the maxmind db reader is been used in asp.net pages.

**Comment by oschwald** [comment]
I am closing this as it should be fixed in `1.1.0-beta1`. Please note that you should be sharing one reader across many threads.
