### ISSUE TITLE
Add support of strongly typed results of Find

### ISSUE THREAD

**Issue by vk5880** [maxmind/MaxMind-DB-Reader-dotnet#50]

**Comment by oschwald** [comment]
Could you clarify what you mean here? We already support strongly typed results as described in the usage documentation.

**Comment by vk5880** [comment]
There is only one type option to get from Find is documented - Dictionary<string, object>. It is not convinient to work with objects of unknown type. What is expected is to get some POCO specific type with set of fields. This would work the best.
Now I forced to hack what data reader provides by writing some tests having db format and csv data documented.

**Comment by vk5880** [comment]
So now, I want to map results of reader to objects similar to:

> public class GeoLiteResult
>     {
>         public City city { get; set; }
>         public Continent continent { get; set; }
>         public Country country { get; set; }
>         public Location location { get; set; }
>     }

**Comment by oschwald** [comment]
As documented, you may decode directly to your own types using the appropriate attributes.

However, is there a reason why you aren't using https://github.com/maxmind/GeoIP2-dotnet, which does this heavy lifting for you?

**Comment by vk5880** [comment]
It's kind of very strange approach. I'm researching this now. Thanks

**Comment by vk5880** [comment]
Sorry, I missed your link to different project "MaxMind.GeoIP2", that has what I asked for. Sorry for bothering you, didn't expected you have 2 clients for GeoLite dbs.
Thank you!
