### ISSUE TITLE
issue - powershell-core

### ISSUE THREAD

**Issue by myjjuliet** [maxmind/MaxMind-DB-Reader-dotnet#89]
Works fine in powershell 5.1.
However, in version 7.1 of the PowerShell-core, the following error occurs.

'[MaxMind.Db.Reader]::new($Database)
Exception calling ".ctor" with "1" argument(s): "Could not load type 'System.IO.MemoryMappedFiles.MemoryMappedFileSecurity' from
     | assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."

**Comment by oschwald** [comment]
This seems a bit out of scope here. Perhaps look at https://github.com/PowerShell/PowerShell/issues/7326 for ideas on how to get it to work. You may need to use one of the .NETStandard DLLs.
